webtalk_init -webtalk_dir D:/MIPS32CPU/thinpad_top/thinpad_top.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  6 22:55:25 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1ce89381-34b2-42d8-87ff-a31c8f90a3bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e0777dd008c45fcbaffd6b18f2c35e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "554912457 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "268.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "270836_KB" -context "xsim\\usage"
webtalk_transmit -clientid 31622097 -regid "" -xml D:/MIPS32CPU/thinpad_top/thinpad_top.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/MIPS32CPU/thinpad_top/thinpad_top.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/MIPS32CPU/thinpad_top/thinpad_top.sim/sim_1/impl/timing/xsim/xsim.dir/tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
